
export const styles = {
    container: {
        padding: '1rem',
        fontFamily: 'var(--vscode-font-family)',
        color: 'var(--vscode-foreground)',
        backgroundColor: 'var(--vscode-editor-background)',
        height: '100%',
    },
    heading: {
        fontSize: '1.2rem',
        fontWeight: 'bold',
        marginBottom: '1rem',
        color: 'var(--vscode-foreground)',
    },
    label: {
        fontSize: '0.85rem',
        marginBottom: '0.25rem',
        display: 'block',
        color: 'var(--vscode-foreground)',
    },
    select: {
        width: '100%',
        padding: '0.5rem',
        fontSize: '0.9rem',
        backgroundColor: 'var(--vscode-input-background)',
        color: 'var(--vscode-input-foreground)',
        border: '1px solid var(--vscode-input-border)',
        borderRadius: '4px',
    },
    selectContainer: {
        position: 'relative',
        width: '100%',
    },
    selectDisplay: {
        width: '100%',
        padding: '0.5rem',
        fontSize: '0.9rem',
        backgroundColor: 'var(--vscode-input-background)',
        color: 'var(--vscode-input-foreground)',
        border: '1px solid var(--vscode-input-border)',
        borderRadius: '4px',
        cursor: 'pointer',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        boxSizing: 'border-box',
    },
    arrow: {
        fontSize: '0.8rem',
        color: 'var(--vscode-descriptionForeground)',
    },
    dropdown: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        backgroundColor: 'var(--vscode-dropdown-background)',
        border: '1px solid var(--vscode-dropdown-border)',
        borderTop: 'none',
        borderRadius: '0 0 4px 4px',
        zIndex: 1000,
        maxHeight: '200px',
        overflow: 'hidden',
    },
    searchInput: {
        width: '100%',
        padding: '0.5rem',
        fontSize: '0.9rem',
        backgroundColor: 'var(--vscode-input-background)',
        color: 'var(--vscode-input-foreground)',
        border: 'none',
        borderBottom: '1px solid var(--vscode-input-border)',
        outline: 'none',
        boxSizing: 'border-box',
    },
    optionsList: {
        maxHeight: '150px',
        overflowY: 'auto',
    },
    option: {
        padding: '0.5rem',
        cursor: 'pointer',
        borderBottom: '1px solid var(--vscode-widget-border)',
        color: 'var(--vscode-foreground)',
    },
    selectedOption: {
        backgroundColor: 'var(--vscode-list-activeSelectionBackground)',
        color: 'var(--vscode-list-activeSelectionForeground)',
    },
    noOptions: {
        padding: '0.5rem',
        color: 'var(--vscode-descriptionForeground)',
        textAlign: 'center',
    },
    button: {
        marginTop: '1.5rem',
        width: '100%',
        padding: '0.6rem',
        fontSize: '0.95rem',
        backgroundColor: 'var(--vscode-button-background)',
        color: 'var(--vscode-button-foreground)',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
    },
    // New styles for git integration
    loading: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100px',
        fontSize: '0.9rem',
        color: 'var(--vscode-descriptionForeground)',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '1rem',
    },
    refreshButton: {
        backgroundColor: 'var(--vscode-button-secondaryBackground)',
        color: 'var(--vscode-button-secondaryForeground)',
        border: '1px solid var(--vscode-button-border)',
        borderRadius: '4px',
        padding: '0.5rem',
        cursor: 'pointer',
        fontSize: '0.9rem',
    },
    warning: {
        backgroundColor: 'var(--vscode-editorWarning-background)',
        color: 'var(--vscode-editorWarning-foreground)',
        padding: '0.5rem',
        borderRadius: '4px',
        fontSize: '0.85rem',
        marginBottom: '1rem',
        textAlign: 'center',
        border: '1px solid var(--vscode-editorWarning-border)',
    },
    // Commit selection styles
    commitSection: {
        marginTop: '1rem',
        padding: '0.75rem',
        backgroundColor: 'var(--vscode-editorWidget-background)',
        borderRadius: '4px',
        border: '1px solid var(--vscode-widget-border, var(--vscode-contrastBorder, #444))',
    },
    loadingText: {
        color: 'var(--vscode-descriptionForeground)',
        fontSize: '0.8rem',
        fontStyle: 'italic',
    },
    commitCount: {
        color: 'var(--vscode-textLink-foreground)',
        fontSize: '0.8rem',
    },
    selectedCommit: {
        marginTop: '0.5rem',
        padding: '0.5rem',
        backgroundColor: 'var(--vscode-list-activeSelectionBackground)',
        color: 'var(--vscode-list-activeSelectionForeground)',
        borderRadius: '4px',
        fontSize: '0.85rem',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        border: '1px solid var(--vscode-contrastActiveBorder, var(--vscode-list-activeSelectionBackground))',
    },
    clearButton: {
        backgroundColor: 'var(--vscode-button-secondaryBackground)',
        color: 'var(--vscode-button-secondaryForeground)',
        border: '1px solid var(--vscode-button-border)',
        borderRadius: '3px',
        padding: '0.25rem 0.5rem',
        fontSize: '0.8rem',
        cursor: 'pointer',
    },
    // Intelligent routing info
    intelligentRoutingInfo: {
        backgroundColor: 'var(--vscode-editorInfo-background)',
        color: 'var(--vscode-editorInfo-foreground)',
        padding: '0.5rem',
        borderRadius: '4px',
        fontSize: '0.65rem',
        marginBottom: '0.5rem',
        border: '1px solid var(--vscode-editorInfo-border, var(--vscode-editorInfo-foreground, #22c55e))',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.5rem',
    },
    intelligentRoutingWarning: {
        backgroundColor: 'var(--vscode-editorWarning-background)',
        color: 'var(--vscode-editorWarning-foreground)',
        padding: '0.5rem',
        borderRadius: '4px',
        fontSize: '0.65rem',
        marginBottom: '0.5rem',
        border: '1px solid var(--vscode-editorWarning-border, var(--vscode-contrastBorder, #f59e0b))',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '0.5rem',
    },
    // Review actions section
    reviewSection: {
        position: 'absolute',
        width: '100%',
        bottom: '0',
        left: '0',
        backgroundColor: 'var(--vscode-editorWidget-background)',
        borderTop: '1px solid var(--vscode-widget-border)',
        padding: '0.75rem',
        boxSizing: 'border-box',
    },
    reviewSectionTitle: {
        fontSize: '0.9rem',
        fontWeight: 'bold',
        marginBottom: '0.75rem',
        color: 'var(--vscode-foreground)',
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
    },
    reviewStatus: {
        fontSize: '0.8rem',
        marginBottom: '1rem',
        padding: '0.5rem',
        borderRadius: '4px',
        backgroundColor: 'var(--vscode-editorInfo-background)',
        color: 'var(--vscode-editorInfo-foreground)',
        border: '1px solid var(--vscode-editorInfo-border)',
    },
    noReviewStatus: {
        fontSize: '0.8rem',
        marginBottom: '1rem',
        padding: '0.5rem',
        borderRadius: '4px',
        backgroundColor: 'var(--vscode-editorError-background)',
        color: 'var(--vscode-editorError-foreground)',
        border: '1px solid var(--vscode-editorError-border)',
    },
    reviewActions: {
        display: 'flex',
        flexDirection: 'row',
        gap: '0.5rem',
        justifyContent: 'space-between',
    },
    actionButton: {
        padding: '0.6rem 0.75rem',
        fontSize: '0.85rem',
        fontWeight: '500',
        borderRadius: '4px',
        border: 'none',
        cursor: 'pointer',
        transition: 'all 0.2s ease',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '0.5rem',
        flex: 1, // Make buttons take equal width
        minHeight: '40px',
    },
    primaryButton: {
        backgroundColor: 'var(--vscode-button-background)',
        color: 'var(--vscode-button-foreground)',
    },
    secondaryButton: {
        backgroundColor: 'var(--vscode-button-secondaryBackground)',
        color: 'var(--vscode-button-secondaryForeground)',
    },
    successButton: {
        backgroundColor: 'var(--vscode-testing-iconPassed)',
        color: 'var(--vscode-button-foreground)',
    },
    disabledButton: {
        backgroundColor: 'var(--vscode-button-secondaryBackground)',
        color: 'var(--vscode-disabledForeground)',
        cursor: 'not-allowed',
        opacity: '0.6',
    },
    infoButton: {
        backgroundColor: 'var(--vscode-button-background)',
        color: 'var(--vscode-button-foreground)',
        border: '1px solid var(--vscode-button-border)',
    },
    settingsButton: {
        backgroundColor: 'var(--vscode-button-secondaryBackground)',
        color: 'var(--vscode-button-secondaryForeground)',
        border: '1px solid var(--vscode-button-border)',
    },
};